/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include "gpio.h"
#include "adc.h"
#include "timer.h"

/*
 *
 * SERVO MOTOR DATA PIN : PA5
 * POTANTIOMETER PIN : PA0
 *
 * */


int main(){


	RCC->CFGR |= 0<<10; // set APB1 = 16 MHz
	
	GPIO_Handle_t PA5 ={GPIOA,{GPIO_PIN_NO_5,GPIO_MODE_ALTERNATE,0,0,0,GPIO_AF1}};
	gpio_init(&PA5);

	pwm_init(TIMER_2, 16, 20000, 500);

	adc_init();
	uint32_t adc_data;

	while(1){

		start_conversation();
		adc_data = adc_read();
		TIMER2->CCR1 = adc_data*1.9+556;
	

	}
}
